[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "mcp[cli]>=1.9.4",
    "uvicorn>=0.34.3",
]
